# Generated by Django 5.0.6 on 2024-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_category_book_book_photo_book_retal_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='state_j',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
