# Generated by Django 5.0.6 on 2024-06-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_state_j'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='state_j',
            new_name='state_book',
        ),
    ]
