# Generated by Django 5.0.6 on 2024-06-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_rename_state_j_book_state_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='state_book',
            new_name='حالة_الكتاب',
        ),
    ]
