# Generated by Django 5.0.6 on 2024-06-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_rename_state_book_book_حالة_الكتاب'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='حالة_الكتاب',
            new_name='state_book',
        ),
    ]
