# Generated by Django 5.0.6 on 2024-06-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_rename_حالة_الكتاب_book_state_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_period',
            new_name='rental_period',
        ),
        migrations.RemoveField(
            model_name='book',
            name='retal_price_day',
        ),
        migrations.AddField(
            model_name='book',
            name='rental_price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
