# Generated by Django 5.0.6 on 2024-06-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_photo',
            field=models.ImageField(default='default ava photo/photo1.png', upload_to='photos', verbose_name='user avatar'),
        ),
    ]
