# Generated by Django 5.0.6 on 2024-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_alter_book_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_photo',
            field=models.ImageField(default='photos/defaultAva/photo1.png', upload_to='photos', verbose_name='user avatar'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(max_length=10),
        ),
    ]
