# Generated by Django 5.0.6 on 2024-06-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_alter_book_author_photo_alter_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='totalrental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_period',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
